In [1]:
import json

path = './corpus.jsonl'

with open(path, 'r') as f:
    corpus = [json.loads(line)['text'] for line in f]

In [17]:
import datasets
dataset = datasets.load_dataset('json', data_files=path, split='train')
dataset

Dataset({
    features: ['text'],
    num_rows: 2587
})

In [18]:
for i in range(10):
    print(dataset[i]['text'])
    print('-' * 100)

does not know that angles in a triangle sum to 180 degrees
----------------------------------------------------------------------------------------------------
uses dividing fractions method for multiplying fractions
----------------------------------------------------------------------------------------------------
believes there are 100 degrees in a full turn
----------------------------------------------------------------------------------------------------
thinks a quadratic without a non variable term, can not be factorised
----------------------------------------------------------------------------------------------------
believes addition of terms and powers of terms are equivalent e.g. a + c = a^c
----------------------------------------------------------------------------------------------------
when measuring a reflex angle, gives the acute or obtuse angle that sums to 360 instead
------------------------------------------------------------------------------------------------

In [21]:
path = "./queries_val2_v1.jsonl"
dataset = datasets.load_dataset('json', data_files=path, split='train')
dataset
for i in range(10):
    print(dataset[i]['query'], dataset[i]['correct_id'])
    print('-' * 100)

simplify an algebraic fraction by factorising the numerator simplify the following, if possible: \( \frac{m^{2}+2 m-3}{m-3} \) \( m+1 \) 2142.0
----------------------------------------------------------------------------------------------------
simplify an algebraic fraction by factorising the numerator simplify the following, if possible: \( \frac{m^{2}+2 m-3}{m-3} \) \( m+2 \) 143.0
----------------------------------------------------------------------------------------------------
simplify an algebraic fraction by factorising the numerator simplify the following, if possible: \( \frac{m^{2}+2 m-3}{m-3} \) \( m-1 \) 2142.0
----------------------------------------------------------------------------------------------------
recall and use the intersecting diagonals properties of a rectangle the angles highlighted on this rectangle with different length sides can never be... ![a rectangle with the diagonals drawn in. the angle on the right hand side at the centre is highlighted in red a

In [28]:
from transformers import AutoTokenizer, AutoModel
model_id = "BAAI/bge-small-en-v1.5"
d = {'text': 'does not know that angles in a triangle sum to 180 degrees'}
tokenizer = AutoTokenizer.from_pretrained(model_id)
ids = tokenizer(d['text'], max_length=128, padding=True, truncation=True,
                             return_tensors="pt")
ids


{'input_ids': tensor([[  101,  2515,  2025,  2113,  2008, 12113,  1999,  1037,  9546,  7680,
          2000,  8380,  5445,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [42]:
import torch
from transformers import AutoTokenizer, AutoModel
model_id = "BAAI/bge-small-en-v1.5"
tokenizer = AutoTokenizer.from_pretrained(model_id)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = AutoModel.from_pretrained(model_id).to(device)

In [43]:
d = {'text': 'uses dividing fractions method for multiplying fractions'}
ids = tokenizer(d['text'], padding=True, truncation=True,
                             return_tensors="pt")
model.eval()
with torch.no_grad():
    ids = ids.to(device)
    outputs = model(**ids)
    # embeddings = last_token_pool(outputs.last_hidden_state, features['attention_mask'])
    embeddings = outputs.last_hidden_state[:, 0]  # CLS token
    embeddings = torch.nn.functional.normalize(embeddings, p=2, dim=1)
    print(embeddings)

tensor([[-5.3867e-02,  3.1994e-03, -1.6951e-02, -6.9049e-02, -3.0075e-02,
         -3.8436e-02, -6.5766e-03, -3.3353e-02,  5.9543e-02,  3.3863e-02,
          1.3753e-02, -7.6120e-02, -1.4235e-02, -1.1288e-02,  2.3966e-02,
         -1.3862e-02, -3.0358e-02,  9.2968e-03, -1.8522e-02, -2.4247e-02,
          9.7753e-03, -4.4002e-02, -1.7134e-02, -7.5372e-03,  8.5100e-02,
          3.4938e-02, -3.3996e-02, -1.2213e-01, -5.3134e-02, -1.7060e-01,
          8.0506e-02,  3.3787e-03,  6.7322e-02, -3.7322e-02, -6.5864e-02,
         -2.4245e-02, -1.3552e-02,  4.5215e-02, -3.1878e-02,  1.7572e-02,
          1.5058e-02, -4.2877e-02,  3.5724e-02, -2.0317e-02, -3.1048e-03,
         -2.0955e-02, -6.5798e-02,  2.2393e-02,  1.0473e-01,  3.3058e-02,
          4.0727e-02, -1.5813e-02, -8.8412e-03,  1.9312e-03, -2.0983e-02,
          2.0654e-02,  4.1578e-02,  3.0341e-02,  1.9466e-02,  2.8379e-02,
          9.3157e-02,  3.2919e-02, -1.3207e-01,  3.1198e-02,  3.6531e-02,
         -6.6946e-02,  2.4984e-02, -2.

In [41]:
from FlagEmbedding import FlagModel
sentences_1 = ["uses dividing fractions method for multiplying fractions"]
model = FlagModel('BAAI/bge-small-en-v1.5',
                  use_fp16=False) # Setting use_fp16 to True speeds up computation with a slight performance degradation
embeddings_1 = model.encode(sentences_1)
print(embeddings_1)


You're using a BertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


[[-5.38667627e-02  3.19937663e-03 -1.69507973e-02 -6.90493658e-02
  -3.00752297e-02 -3.84360589e-02 -6.57658745e-03 -3.33531164e-02
   5.95430210e-02  3.38625535e-02  1.37533555e-02 -7.61200637e-02
  -1.42346853e-02 -1.12881511e-02  2.39661802e-02 -1.38618322e-02
  -3.03578936e-02  9.29683819e-03 -1.85216218e-02 -2.42465585e-02
   9.77529120e-03 -4.40022238e-02 -1.71339009e-02 -7.53717171e-03
   8.51000249e-02  3.49384509e-02 -3.39957103e-02 -1.22133195e-01
  -5.31342402e-02 -1.70595080e-01  8.05058479e-02  3.37874098e-03
   6.73223808e-02 -3.73220108e-02 -6.58638924e-02 -2.42451373e-02
  -1.35524701e-02  4.52145375e-02 -3.18779461e-02  1.75721496e-02
   1.50582353e-02 -4.28771637e-02  3.57243642e-02 -2.03169417e-02
  -3.10484786e-03 -2.09549014e-02 -6.57979324e-02  2.23932322e-02
   1.04728520e-01  3.30577679e-02  4.07274663e-02 -1.58129372e-02
  -8.84115789e-03  1.93124672e-03 -2.09827367e-02  2.06543542e-02
   4.15777266e-02  3.03407162e-02  1.94660835e-02  2.83791404e-02
   9.31568

In [22]:
np.array([query_embedding])

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

In [23]:
import faiss
import numpy as np
# import torch

# 1. 初始化索引
dimension = 384  # BGE-small 模型的输出维度
index = faiss.IndexFlatL2(dimension)  # 使用L2距离的暴力检索索引

# 2. 将语料库的向量添加到索引中
# 假设 corpus_embeddings 是您的语料库编码后的向量
corpus_embeddings = np.zeros((50, dimension))
index.add(corpus_embeddings.astype('float32'))

# 3. 搜索最相似的向量
query_embedding = np.zeros(dimension)
k = 5  # 返回前k个最相似的结果

# 执行搜索
distances, indices = index.search(
    np.array([query_embedding]).astype('float32'), 
    k
)

In [15]:
distances, indices

(array([[0., 0., 0., 0., 0.]], dtype=float32), array([[1, 2, 3, 4, 0]]))

In [29]:
indices[:, :2]

array([[1, 2]])

In [57]:
import numpy as np


def apk(actual, predicted, k=25):
    """
    Computes the average precision at k.
    
    This function computes the average prescision at k between two lists of
    items.
    
    Parameters
    ----------
    actual : list of float
    predicted : numpy.ndarray
    k : int, optional
        The maximum number of predicted elements
        
    Returns
    -------
    score : double
            The average precision at k over the input lists
    """
    
    if not actual:
        return 0.0
    print(len(predicted))
    if len(predicted)>k:
        predicted = predicted[:k]

    score = 0.0
    num_hits = 0.0

    for i,p in enumerate(predicted):
        print(p, actual)
        # first condition checks whether it is valid prediction
        # second condition checks if prediction is not repeated
        if p in actual and p not in predicted[:i]:
            print("hit")
            num_hits += 1.0
            score += num_hits / (i+1.0)

    return score / min(len(actual), k)

def mapk(actual, predicted, k=25):
    """
    Computes the mean average precision at k.
    
    This function computes the mean average prescision at k between two lists
    of lists of items.
    
    Parameters
    ----------
    actual : list
             A list of lists of elements that are to be predicted 
             (order doesn't matter in the lists)
    predicted : list
                A list of lists of predicted elements
                (order matters in the lists)
    k : int, optional
        The maximum number of predicted elements
        
    Returns
    -------
    score : double
            The mean average precision at k over the input lists
    """
    res = [apk(a,p,k) for a,p in zip(actual, predicted)]
    print(res)
    return np.mean(res)


In [60]:
type(predicted)

numpy.ndarray

In [61]:
actual = [1, 2]
predicted = np.array([[2,2,1], [1,2,3]])
mapk(actual, predicted)

3
2 1


TypeError: argument of type 'int' is not iterable

In [8]:
from transformers import AutoTokenizer, AutoModel
import torch
from torch import Tensor
from torch.nn.functional import normalize
def last_token_pool(last_hidden_states: Tensor,
                 attention_mask: Tensor) -> Tensor:
    left_padding = (attention_mask[:, -1].sum() == attention_mask.shape[0])
    if left_padding:
        return last_hidden_states[:, -1]
    else:
        sequence_lengths = attention_mask.sum(dim=1) - 1
        batch_size = last_hidden_states.shape[0]
        return last_hidden_states[torch.arange(batch_size, device=last_hidden_states.device), sequence_lengths]
    
model_path = "BAAI/bge-en-icl"
tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModel.from_pretrained(model_path)
model.eval()
txt = 'Does not know that angles in a triangle sum to 180 degrees'
with torch.no_grad():
    ids = tokenizer(txt, padding=True, truncation=True,
                             return_tensors="pt")
    outputs = model(**ids)
    embedding = last_token_pool(outputs.last_hidden_state, ids['attention_mask'])
    embedding = normalize(embedding, p=2, dim=1)

Loading checkpoint shards: 100%|██████████| 3/3 [00:00<00:00,  8.21it/s]
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


In [9]:
ids

{'input_ids': tensor([[    1,  9377,   459,   873,   369, 22289,   297,   264, 24411,  2648,
           298, 28705, 28740, 28783, 28734, 11182,     2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [11]:
embedding

tensor([[-0.0074,  0.0133, -0.0022,  ...,  0.0184,  0.0069, -0.0021]])

In [5]:
outputs = model(**batch_dict)
embedding = last_token_pool(outputs.last_hidden_state, batch_dict['attention_mask'])
embedding = F.normalize(embedding, p=2, dim=1)

torch.Size([1, 17, 4096])

In [6]:
from torch.nn.functional import normalize
normalized_lst = normalize(lst, p=2, dim=1)
normalized_lst.shape


torch.Size([1, 17, 4096])

In [7]:
normalized_lst

tensor([[[-0.1049,  0.1073, -0.1632,  ..., -0.0285, -0.0711,  0.2009],
         [-0.5135,  0.2664,  0.1845,  ...,  0.0845,  0.2855,  0.3079],
         [ 0.0967, -0.2451,  0.0729,  ...,  0.0800,  0.1363, -0.0667],
         ...,
         [ 0.0801,  0.1629,  0.1332,  ..., -0.2446,  0.1674, -0.0064],
         [-0.0601, -0.0237, -0.3550,  ...,  0.4665,  0.2247,  0.3120],
         [-0.1397,  0.4116, -0.0410,  ...,  0.3408,  0.0493, -0.0320]]])

In [4]:
import faiss
import numpy as np
index = faiss.IndexFlatL2(4)
corpus_embeddings = np.array([[1, 2, 3, 4], [2, 3, 4, 5], [1,2,3,4]])
index.add(corpus_embeddings.astype('float32'))


In [17]:
import pandas as pd
mis_map = pd.read_csv('./raw_data/misconception_mapping.csv')
mis_map[mis_map['MisconceptionId'] == 2068]['MisconceptionName'].values[0]

'Does not know that to factorise a quadratic expression, to find two numbers that add to give the coefficient of the x term, and multiply to give the non variable term\n\n'

In [9]:
query_embedding = np.array([[1,2,3,4], [2,3,4,5]])
distances, indices = index.search(query_embedding.astype('float32'), k=3)
indices


array([[0, 2, 1],
       [1, 0, 2]])

In [7]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_sims = cosine_similarity(query_embedding, corpus_embeddings)
val_sorted_indices = np.argsort(-cosine_sims, axis=1)
val_sorted_indices

array([[0, 2, 1]])

In [41]:
import numpy as np
import pandas as pd

def apk(actual, predicted, k=25):
    """
    Computes the average precision at k.
    
    This function computes the average prescision at k between two lists of
    items.
    
    Parameters
    ----------
    actual : list of float
    predicted : numpy.ndarray
    k : int, optional
        The maximum number of predicted elements
        
    Returns
    -------
    score : double
            The average precision at k over the input lists
    """
    
    if not actual:
        return 0.0

    if len(predicted)>k:
        predicted = predicted[:k]

    score = 0.0
    num_hits = 0.0

    for i,p in enumerate(predicted):
        # first condition checks whether it is valid prediction
        # second condition checks if prediction is not repeated
        if p in actual and p not in predicted[:i]:
            num_hits += 1.0
            score += num_hits / (i+1.0)

    return score / min(len(actual), k)


def mapk(actual, predicted, k=25):
    """
    Computes the mean average precision at k.
    
    This function computes the mean average prescision at k between two lists
    of lists of items.
    
    Parameters
    ----------
    actual : list
             A list of lists of elements that are to be predicted 
             (order doesn't matter in the lists)
    predicted : list
                A list of lists of predicted elements
                (order matters in the lists)
    k : int, optional
        The maximum number of predicted elements
        
    Returns
    -------
    score : double
            The mean average precision at k over the input lists
    """
    print([apk(a,p,k) for a,p in zip(actual, predicted)])
    return np.mean([apk(a,p,k) for a,p in zip(actual, predicted)])


def mean_average_precision_at_k(ground_truth, sorted_indices, k):
    """
    Calculate MAP@k for cases with a single ground truth per query.
    Skip queries with NaN ground truth.

    Parameters:
    - ground_truth: A list where each entry is a single relevant item ID or NaN.
    - sorted_indices: A list of lists, where each inner list contains sorted retrieved item IDs for a query.
    - k: The cutoff value for the top-k retrieved items.

    Returns:
    - MAP@k across valid queries.
    """
    valid_aps = []

    for gt, retrieved in zip(ground_truth, sorted_indices):
        # if not np.isnan(gt):
        if pd.notna(gt):
            # Get first k predictions
            retrieved_at_k = retrieved[:k]
            # Find where the ground truth appears in the top k predictions
            gt_positions = np.where(retrieved_at_k == gt)[0]
            if len(gt_positions) > 0:
                # Add 1 because position is 0-based
                rank = gt_positions[0] + 1
                valid_aps.append(1 / rank)
            else:
                valid_aps.append(0)
    print(valid_aps)
    return np.mean(valid_aps) if valid_aps else np.nan

def recall_at_k(ground_truth, predicted_indices, k=25):
    """
    Calculate Recall@k for cases with a single ground truth per query.
    Skip queries with NaN ground truth.

    Parameters:
    - ground_truth: A list where each entry is a single relevant item ID or NaN.
    - sorted_indices: A list of lists, where each inner list contains sorted retrieved item IDs for a query.
    - k: The cutoff value for the top-k retrieved items.

    Returns:
    - Average Recall@k across valid queries.
    """
    valid_recalls = []

    for gt, retrieved in zip(ground_truth, predicted_indices):
        # if not np.isnan(gt):
        if pd.notna(gt):
            if gt in retrieved[:k]:
                valid_recalls.append(1)
            else:
                valid_recalls.append(0)

    return np.mean(valid_recalls) if valid_recalls else np.nan

In [42]:
correct_ids = [np.nan, 2.0, 3.0, 4.0]
predicted_ids = np.array([
    [2, 3, 4, 5],
    [1, 2, 3, 4],
    [1, 2, 3, 4],
    [1, 2, 3, 4],
])
mean_average_precision_at_k(correct_ids, np.array(predicted_ids), k=4)

# mapk([[id] for id in correct_ids], predicted_ids, 4)

[np.float64(0.5), np.float64(0.3333333333333333), np.float64(0.25)]


np.float64(0.3611111111111111)

In [43]:
mapk([[id] for id in correct_ids], predicted_ids, 4)

[0.0, 0.5, 0.3333333333333333, 0.25]


np.float64(0.2708333333333333)

In [33]:
mean_average_precision_at_k(correct_ids, np.array(predicted_ids), k=4)


[0, np.float64(0.5), np.float64(0.3333333333333333), np.float64(0.25)]


np.float64(0.2708333333333333)

In [9]:
import gc
gc.collect()
torch.cuda.empty_cache()

In [11]:
!nvidia-smi

Wed Dec  4 20:10:14 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.67                 Driver Version: 550.67         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        On  |   00000000:0A:00.0 Off |                  N/A |
| 30%   30C    P8             20W /  350W |   24220MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


In [1]:
from transformers import AutoTokenizer, AutoModel
import torch
tokenizer = AutoTokenizer.from_pretrained("BAAI/bge-en-icl")
model = AutoModel.from_pretrained("BAAI/bge-en-icl")
device = 'cuda:0' if torch.cuda.is_available() else 'cpu'
model.half()
model.to(device)
model.eval()



/root/miniconda3/envs/kaggle_nlp/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Loading checkpoint shards: 100%|██████████| 3/3 [00:00<00:00,  9.23it/s]


MistralModel(
  (embed_tokens): Embedding(32003, 4096)
  (layers): ModuleList(
    (0-31): 32 x MistralDecoderLayer(
      (self_attn): MistralSdpaAttention(
        (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
        (k_proj): Linear(in_features=4096, out_features=1024, bias=False)
        (v_proj): Linear(in_features=4096, out_features=1024, bias=False)
        (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
        (rotary_emb): MistralRotaryEmbedding()
      )
      (mlp): MistralMLP(
        (gate_proj): Linear(in_features=4096, out_features=14336, bias=False)
        (up_proj): Linear(in_features=4096, out_features=14336, bias=False)
        (down_proj): Linear(in_features=14336, out_features=4096, bias=False)
        (act_fn): SiLU()
      )
      (input_layernorm): MistralRMSNorm((4096,), eps=1e-05)
      (post_attention_layernorm): MistralRMSNorm((4096,), eps=1e-05)
    )
  )
  (norm): MistralRMSNorm((4096,), eps=1e-05)
)

In [4]:
txt = 'Mo salah is a football player'
with torch.no_grad():
    ids = tokenizer(txt, padding=True, truncation=True,
                             return_tensors="pt")
    ids = {k: v.to(device) for k, v in ids.items()}
    outputs = model(**ids)

In [11]:
import pandas as pd
raw_data = pd.read_csv('./raw_data/train.csv')

In [12]:
# split 1
question_ids = sorted(raw_data["QuestionId"].unique())
val_size = int(len(question_ids) * 0.2)
val_question_ids_1 = question_ids[-val_size:]
train_question_ids_1 = question_ids[:-val_size]

train_data_1 = raw_data[raw_data["QuestionId"].isin(train_question_ids_1)]
val_data_1 = raw_data[raw_data["QuestionId"].isin(val_question_ids_1)]
train_data_1.shape, val_data_1.shape

((1496, 15), (373, 15))

In [15]:
train_data_1.head()

QuestionId  ConstructId                                      ConstructName  \
0           0          856  Use the order of operations to carry out calcu...   
1           1         1612  Simplify an algebraic fraction by factorising ...   
2           2         2774            Calculate the range from a list of data   
3           3         2377  Recall and use the intersecting diagonals prop...   
4           4         3387  Substitute positive integer values into formul...   

   SubjectId                                        SubjectName CorrectAnswer  \
0         33                                             BIDMAS             A   
1       1077                    Simplifying Algebraic Fractions             D   
2        339  Range and Interquartile Range from a List of Data             B   
3         88                       Properties of Quadrilaterals             C   
4         67                          Substitution into Formula             A   

                                        QuestionText            AnswerAText  \
0  \[\n3 \times 2+4-5\n\]\nWhere do the brackets ...  \( 3 \times(2+4)-5 \)   
1  Simplify the following, if possible: \( \frac{...              \( m+1 \)   
2  Tom and Katie are discussing the \( 5 \) plant...              Only\nTom   
3  The angles highlighted on this rectangle with ...                  acute   
4  The equation \( f=3 r^{2}+3 \) is used to find...               \( 30 \)   

              AnswerBText            AnswerCText             AnswerDText  \
0  \( 3 \times 2+(4-5) \)  \( 3 \times(2+4-5) \)  Does not need brackets   
1               \( m+2 \)              \( m-1 \)       Does not simplify   
2             Only\nKatie     Both Tom and Katie      Neither is correct   
3                  obtuse       \( 90^{\circ} \)  Not enough information   
4                \( 27 \)               \( 51 \)                \( 24 \)   

   MisconceptionAId  MisconceptionBId  MisconceptionCId  MisconceptionDId  
0               NaN               NaN               NaN            1672.0  
1            2142.0             143.0            2142.0               NaN  
2            1287.0               NaN            1287.0            1073.0  
3            1180.0            1180.0               NaN            1180.0  
4               NaN               NaN               NaN            1818.0

In [14]:
# split 2
import numpy as np
np.random.seed(42)
question_ids = sorted(raw_data["QuestionId"].unique())
val_question_ids_2 = np.random.choice(question_ids, int(len(question_ids) * 0.2), replace=False)

train_data_2 = raw_data[~raw_data["QuestionId"].isin(val_question_ids_2)]
val_data_2 = raw_data[raw_data["QuestionId"].isin(val_question_ids_2)]
train_data_2.shape, val_data_2.shape

((1496, 15), (373, 15))

In [18]:
val_question_ids_2

array([1700, 1488,  921,  275,  416, 1654,  247,  383,  322,  203,  873,
       1111, 1302,  352, 1376,  575, 1345,  479,  942, 1660,  305,  514,
       1189, 1501,  529,  620, 1749,  366, 1811, 1105,  764,  394, 1790,
        464, 1054,  946, 1497, 1859, 1107, 1607,  806,  111,  582, 1033,
       1339,  298,  879, 1843, 1206,  887, 1272, 1170,  297, 1712, 1085,
        544, 1791, 1619, 1244,   65, 1204,  462, 1318, 1569,  239,  188,
       1847,   29, 1335, 1288,  759, 1160, 1544,  398,  836,  109,  637,
       1258, 1161,  932,  705,  617,  799, 1061,  432, 1110, 1142,  619,
        706,  425, 1797,  591,  495, 1290, 1737,  727,  196,  344,  135,
        218,  270,  433, 1190, 1765, 1005, 1387,  526,  237,  818,  943,
        450,  707,  598, 1348, 1549, 1247,  930,  422, 1236, 1726, 1221,
        254, 1087, 1309, 1573,  307,   70, 1667,  324, 1594, 1381,  611,
        570, 1036,  561, 1713, 1458, 1168,  631,  212,   23,  289,   63,
        869,  534, 1674, 1546, 1440, 1089, 1245,  9

In [33]:
# set of subject id in train_data_1 and val_data_1
len(set(train_data_1["QuestionId"].unique()) & set(val_data_1["QuestionId"].unique()))

0

In [29]:
# set of subject id in train_data_2 and val_data_2
len(set(train_data_2["QuestionId"].unique()) & set(val_data_2["QuestionId"].unique()))

0

In [20]:
val_data_2.head()

QuestionId  ConstructId  \
23          23         2742   
29          29         1045   
30          30         3515   
32          32         1484   
44          44         2440   

                                        ConstructName  SubjectId  \
23  Interpret sloping linear sections of a displac...         58   
29  Solve linear inequalities in one variable wher...        166   
30  Determine the function of a single function ma...        649   
32  Solve linear equations with the variable appea...         64   
44  Identify a right-angled triangle when presente...        175   

                    SubjectName CorrectAnswer  \
23             Real Life Graphs             A   
29  Solving Linear Inequalities             B   
30            Function Machines             A   
32             Linear Equations             D   
44      Properties of Triangles             C   

                                         QuestionText  \
23  This graph shows how far Fido the dog is from ...   
29                    Solve\n\[\n2 n+3 \leq 3 n-7\n\]   
30  Tom and Katie are discussing this function mac...   
32  Which of the following is a correct first step...   
44  \( A B C D \) is a rectangle.\nWhat type of tr...   

                AnswerAText             AnswerBText           AnswerCText  \
23     Fido is walking home  Fido has fallen asleep  Fido is accelerating   
29           \( 2 \leq n \)         \( 10 \leq n \)       \( n \leq 10 \)   
30                Only\nTom              Only Katie    Both Tom and Katie   
32  \( \frac{2 r}{5}=5+r \)    \( 10 r-15=10+5 r \)      \( 2 r-3=10+r \)   
44                  Scalene               Isosceles          Right-angled   

                       AnswerDText  MisconceptionAId  MisconceptionBId  \
23  Fido is walking away from home               NaN            2492.0   
29                 \( -4 \leq n \)            1214.0               NaN   
30              Neither is correct               NaN               NaN   
32              \( 2 r-3=10+5 r \)            1566.0              98.0   
44                     Equilateral             646.0            1970.0   

    MisconceptionCId  MisconceptionDId  
23            2032.0            2437.0  
29             811.0            1214.0  
30             220.0               NaN  
32             347.0               NaN  
44               NaN            1970.0